# Generated by Django 3.2.6 on 2021-10-15 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='is_child',
            field=models.BooleanField(default=False),
        ),
    ]
