# Generated by Django 3.2.6 on 2021-11-22 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='annotation',
            field=models.TextField(default='', max_length=300, null=True, verbose_name='Аннотация'),
        ),
        migrations.AddField(
            model_name='profile',
            name='position',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='Должность'),
        ),
    ]
