# Generated by Django 3.2.6 on 2021-10-07 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_app_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apps', to='shop.category', verbose_name='Категория'),
        ),
    ]
